// Supabase Edge Function: resolve-symbols
// The AAC symbol engine (AAC_STUDIO_PLAN.md §2) — resolves concepts to real AAC symbol
// images, once per concept, reused across every material forever.
//
// CHAIN (v4, 2026-07-17): cache → Mulberry Symbols → Imagen + vision QA.
// ARASAAC was the original primary source but the Government of Aragón confirmed by
// email (2026-07-17) that NO commercial licensing mechanism exists for its pictograms
// ("There is no set a commercial license by our government") — and NeuroNest plans to
// commercialize. Mulberry Symbols (mulberrysymbols.org, CC BY-SA 4.0, © Steve Lee) is
// the largest commercial-safe classic AAC set (~3,100 symbols); everything it lacks is
// generated by the Imagen+QA pipeline and owned outright. Attribution for Mulberry is
// printed on every material (aacViewers.tsx). Legacy 'arasaac' rows may exist in
// aac_symbols but the chain no longer produces them.
//
// Mulberry is searched through the Global Symbols public API (globalsymbols.com,
// symbolset_id 13 = Mulberry; the symbolset query param is unreliable so results are
// filtered client-side). Mulberry labels are English-only, so non-English concepts are
// first translated to an English search term by the fast tier; the concept KEY stays in
// the material's language. Images are SVG — stored as-is (renders fine in <img> and
// print); no vision QA needed because we only accept exact / all-token label matches
// from a curated single-label set (unlike ARASAAC's noisy keyword search, which once
// returned a car wash for "wash hands").
//
// External fetches MUST happen here, not Vercel — Vercel's network sandbox blocks all
// external domains except api.anthropic.com (CLAUDE.md §6).
//
// Input: { concepts: [{ concept, language?, symbol_description? }] }
// ACKs immediately and resolves via EdgeRuntime.waitUntil — callers render an emoji
// fallback until symbols land, so nothing ever blocks on this.
//
// Same conventions as the other functions: NOT auto-deployed from git (redeploy manually
// via Supabase MCP deploy_edge_function or `supabase functions deploy resolve-symbols`,
// verify_jwt: false), x-cron-secret auth (shared WEEKLY_FOCUS_CRON_SECRET), secrets from
// env or Vault via the service-role-locked neuronest.get_secret RPC.

import { createClient } from 'npm:@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-cron-secret',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

const supabase = createClient(
  Deno.env.get('SUPABASE_URL')!,
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  { db: { schema: 'neuronest' } }
)

const MULBERRY_SYMBOLSET_ID = 13

type ConceptRequest = { concept: string; language?: string; symbol_description?: string }

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const expected = await getSecret('WEEKLY_FOCUS_CRON_SECRET')
    const provided = req.headers.get('x-cron-secret')
    if (!expected || provided !== expected) {
      return json({ error: 'unauthorized' }, 401)
    }

    const body = await req.json().catch(() => ({}))
    const requested = (body.concepts || []) as ConceptRequest[]
    if (!Array.isArray(requested) || !requested.length) {
      return json({ error: 'concepts required' }, 400)
    }

    // Normalize + de-dupe up front so the cache key is stable no matter how callers spell it
    const seen = new Set<string>()
    const concepts: { concept: string; language: string; symbol_description?: string }[] = []
    for (const r of requested) {
      const concept = String(r.concept || '').trim().toLowerCase()
      const language = String(r.language || 'en').trim().toLowerCase()
      if (!concept) continue
      const key = `${language}:${concept}`
      if (seen.has(key)) continue
      seen.add(key)
      concepts.push({ concept, language, symbol_description: r.symbol_description })
    }
    if (!concepts.length) return json({ error: 'no valid concepts' }, 400)

    // Everything already cached needs no work — report it in the ACK so callers can
    // render those symbols immediately
    const { data: cachedRows } = await supabase.from('aac_symbols')
      .select('concept, language')
      .in('concept', concepts.map(c => c.concept))
    const cachedKeys = new Set((cachedRows || []).map(r => `${r.language}:${r.concept}`))
    const pending = concepts.filter(c => !cachedKeys.has(`${c.language}:${c.concept}`))
    const cachedCount = concepts.length - pending.length

    if (pending.length) {
      // ACK now, resolve in the background — the caller must never wait for fetch/Imagen
      // deno-lint-ignore no-explicit-any
      ;(globalThis as any).EdgeRuntime?.waitUntil?.(resolveAll(pending))
        ?? resolveAll(pending)
    }

    return json({
      ok: true,
      cached: cachedCount,
      resolving: pending.length,
      status: pending.length ? 'resolving in background' : 'all cached',
    })
  } catch (err) {
    console.error('resolve-symbols error:', err)
    return json({ error: String(err) }, 500)
  }
})

async function resolveAll(concepts: { concept: string; language: string; symbol_description?: string }[]) {
  for (const c of concepts) {
    try {
      await resolveOne(c.concept, c.language, c.symbol_description)
    } catch (err) {
      console.error(`resolve '${c.concept}' (${c.language}):`, err)
    }
  }
  console.log(`resolve-symbols done: ${concepts.length} concepts`)
}

async function resolveOne(concept: string, language: string, symbolDescription?: string) {
  // Re-check the cache inside the background task — concurrent invocations may race
  const { data: cached } = await supabase.from('aac_symbols')
    .select('id').eq('concept', concept).eq('language', language).maybeSingle()
  if (cached) { console.log(`'${concept}': cached`); return }

  // 1) Mulberry — commercial-safe, professionally drawn. English labels only, so
  // translate the search term when the concept is in another language (the concept
  // KEY keeps the material's language).
  const searchTerm = language === 'en' ? concept : await translateToEnglish(concept)
  if (searchTerm) {
    const mulberry = await tryMulberry(searchTerm)
    if (mulberry) {
      const storagePath = await uploadSymbol(concept, language, mulberry.bytes, 'svg')
      if (storagePath) {
        await saveSymbol({
          concept, language, source: 'mulberry', arasaac_id: null,
          storage_path: storagePath, symbol_description: symbolDescription || null, qa_passed: true,
        })
        console.log(`'${concept}': Mulberry "${mulberry.label}"`)
        return
      }
    }
  }

  // 2) Imagen + vision QA — for everything Mulberry lacks; these symbols are owned
  // outright (no third-party license at all)
  const generated = await tryGenerate(concept, symbolDescription)
  if (generated) {
    const storagePath = await uploadSymbol(concept, language, generated, 'png')
    if (storagePath) {
      await saveSymbol({
        concept, language, source: 'generated', arasaac_id: null,
        storage_path: storagePath, symbol_description: symbolDescription || null, qa_passed: true,
      })
      console.log(`'${concept}': generated`)
      return
    }
  }

  console.error(`'${concept}': unresolved (no Mulberry match, generation failed) — emoji fallback stays`)
}

// ─── Mulberry via Global Symbols ────────────────────────────────────────────
// GET https://globalsymbols.com/api/v1/labels/search?query=X&language=eng&language_iso_format=639-3
// Returns [{ text, picto: { symbolset_id, image_url } }]. Filter to symbolset 13
// (Mulberry) client-side; accept only exact or all-token label matches — a curated
// single-label set makes fuzzy hits far riskier than misses (Imagen covers misses).
async function tryMulberry(term: string): Promise<{ label: string; bytes: Uint8Array } | null> {
  try {
    const res = await fetch(
      `https://globalsymbols.com/api/v1/labels/search?query=${encodeURIComponent(term)}&language=eng&language_iso_format=639-3&limit=40`,
      { headers: { Accept: 'application/json' } }
    )
    if (!res.ok) { console.error(`Global Symbols search '${term}' ${res.status}`); return null }
    const results = await res.json() as { text?: string; picto?: { symbolset_id?: number; image_url?: string } }[]
    if (!Array.isArray(results)) return null

    const mulberry = results.filter(r => r.picto?.symbolset_id === MULBERRY_SYMBOLSET_ID && r.picto?.image_url)
    if (!mulberry.length) return null

    const tokens = term.toLowerCase().split(/\s+/)
    const score = (label: string): number => {
      const l = label.trim().toLowerCase()
      if (l === term.toLowerCase()) return 0
      const words = l.split(/[\s,]+/)
      if (tokens.every(t => words.includes(t))) return 1
      return 2
    }
    const ranked = mulberry
      .map(r => ({ r, s: score(r.text || '') }))
      .filter(x => x.s <= 1)
      .sort((a, b) => a.s - b.s)
    if (!ranked.length) return null

    const pick = ranked[0].r
    const imgRes = await fetch(pick.picto!.image_url!)
    if (!imgRes.ok) { console.error(`Mulberry image ${imgRes.status}`); return null }
    return { label: pick.text || term, bytes: new Uint8Array(await imgRes.arrayBuffer()) }
  } catch (e) {
    console.error(`Mulberry '${term}':`, e)
    return null
  }
}

// Non-English concepts search Mulberry through a fast-tier translation ("eple" → "apple")
const TRANSLATE_MODELS = ['claude-haiku-4-5', 'claude-sonnet-5']
async function translateToEnglish(concept: string): Promise<string | null> {
  const key = await getSecret('ANTHROPIC_API_KEY')
  if (!key) return null
  for (const model of TRANSLATE_MODELS) {
    try {
      const res = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': key,
          'anthropic-version': '2023-06-01',
        },
        body: JSON.stringify({
          model,
          max_tokens: 30,
          messages: [{
            role: 'user',
            content: `Translate this AAC symbol concept keyword to English. Reply with ONLY the English keyword (1-3 lowercase words), nothing else: "${concept}"`,
          }],
        }),
      })
      if (res.status === 404) continue
      if (!res.ok) { console.error(`translate ${model} ${res.status}`); continue }
      const data = await res.json()
      const text = data.content?.find((b: { type: string }) => b.type === 'text')?.text?.trim().toLowerCase()
      if (text && text.length < 60) return text.replace(/["'.]/g, '')
    } catch (e) { console.error(`translate ${model}:`, e) }
  }
  return null
}

// ─── Imagen fallback ────────────────────────────────────────────────────────
async function tryGenerate(concept: string, symbolDescription?: string): Promise<Uint8Array | null> {
  const GEMINI_KEY = await getSecret('GEMINI_API_KEY')
  if (!GEMINI_KEY) { console.error('GEMINI_API_KEY not available'); return null }

  const prompt = buildAacPrompt(concept, symbolDescription)
  for (let attempt = 0; attempt < 3; attempt++) {
    if (attempt > 0) await new Promise(r => setTimeout(r, 1500))
    const b64 = await tryImagen(prompt, GEMINI_KEY)
    if (!b64) continue
    const verdict = await qaSymbol(b64, concept)
    if (verdict.pass) return Uint8Array.from(atob(b64), ch => ch.charCodeAt(0))
    console.error(`'${concept}' attempt ${attempt + 1}: QA rejected — ${verdict.reason}`)
  }
  return null
}

// AAC symbol conventions (Widgit/Boardmaker/PCS): ONE concept, flat colour, bold outline,
// white background, no text, never a depicted child. Natural scene-first phrasing —
// attribute-list prompts make Imagen render garbled spec sheets (CLAUDE.md §6).
function buildAacPrompt(concept: string, symbolDescription?: string): string {
  const scene = symbolDescription || concept
  return `A very simple flat cartoon pictogram for a children's picture communication card, showing ${scene}. The drawing has thick black outlines and solid bright colours on a pure white background, drawn in the plain minimal style of Widgit and Boardmaker pictograms. The image contains only this one centred drawing and nothing else — no words, no labels, no borders.`
}

// Vision QA for GENERATED symbols: fails open on QA-infrastructure errors, fails
// closed on actual rejection. (Mulberry needs no QA — curated labels, exact matches.)
const QA_MODELS = ['claude-haiku-4-5', 'claude-sonnet-5']
async function qaSymbol(b64: string, word: string): Promise<{ pass: boolean; reason: string }> {
  const key = await getSecret('ANTHROPIC_API_KEY')
  if (!key) return { pass: true, reason: 'QA unavailable (no key) — accepted' }
  const question = `This image is meant to be a flat cartoon pictogram for a young child's AAC communication card meaning "${word}" (the word may be in any language — judge the meaning). Judge it. pass=true ONLY if ALL hold: it is a simple flat cartoon/pictogram (NOT a photograph, NOT photorealistic); it shows one clear concept a young child could read as "${word}"; the background is plain white or near-white; there is NO visible text, letters, numbers, labels, dimension lines, or diagram elements anywhere.`
  for (const model of QA_MODELS) {
    try {
      const res = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': key,
          'anthropic-version': '2023-06-01',
        },
        body: JSON.stringify({
          model,
          max_tokens: 300,
          messages: [{
            role: 'user',
            content: [
              { type: 'image', source: { type: 'base64', media_type: 'image/png', data: b64 } },
              { type: 'text', text: question },
            ],
          }],
          output_config: {
            format: {
              type: 'json_schema',
              schema: {
                type: 'object', additionalProperties: false, required: ['pass', 'reason'],
                properties: { pass: { type: 'boolean' }, reason: { type: 'string' } },
              },
            },
          },
        }),
      })
      if (res.status === 404) { console.error(`QA model ${model} not found — trying next`); continue }
      if (!res.ok) { console.error(`QA ${model} ${res.status}: ${(await res.text()).slice(0, 150)}`); continue }
      const data = await res.json()
      if (data.stop_reason === 'refusal') return { pass: true, reason: 'QA refusal — accepted' }
      const text = data.content?.find((b: { type: string }) => b.type === 'text')?.text
      if (!text) continue
      return JSON.parse(text)
    } catch (e) { console.error(`QA ${model}:`, e) }
  }
  return { pass: true, reason: 'QA infrastructure failed — accepted' }
}

async function tryImagen(prompt: string, key: string): Promise<string | null> {
  const models = ['imagen-4.0-generate-001', 'imagen-4.0-fast-generate-001']
  for (const model of models) {
    try {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${model}:predict?key=${key}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            instances: [{ prompt }],
            parameters: {
              sampleCount: 1,
              aspectRatio: '1:1',
              safetySetting: 'block_low_and_above',
            },
          }),
        }
      )
      const text = await res.text()
      if (!res.ok) {
        console.error(`${model} ${res.status}: ${text.slice(0, 200)}`)
        continue
      }
      const data = JSON.parse(text)
      const b64 = data?.predictions?.[0]?.bytesBase64Encoded
      if (b64) { console.log(`${model}: success`); return b64 }
      console.error(`${model}: empty response (safety filter likely triggered)`)
    } catch (e) { console.error(`${model}:`, e) }
  }
  return null
}

// ─── Storage + table ────────────────────────────────────────────────────────
async function uploadSymbol(concept: string, language: string, bytes: Uint8Array, ext: 'png' | 'svg'): Promise<string | null> {
  const slug = concept.normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/æ/g, 'ae').replace(/ø/g, 'o').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'symbol'
  const storagePath = `aac-symbols/${language}/${slug}.${ext}`
  const { error } = await supabase.storage
    .from('neuronest-documents')
    .upload(storagePath, bytes, { contentType: ext === 'svg' ? 'image/svg+xml' : 'image/png', upsert: true })
  if (error) { console.error(`upload '${concept}':`, error.message); return null }
  return storagePath
}

async function saveSymbol(row: Record<string, unknown>) {
  const { error } = await supabase.from('aac_symbols')
    .upsert(row, { onConflict: 'concept,language' })
  if (error) console.error(`save '${row.concept}':`, error.message)
}

const secretCache: Record<string, string> = {}
async function getSecret(name: string): Promise<string | null> {
  const fromEnv = Deno.env.get(name)
  if (fromEnv) return fromEnv
  if (secretCache[name]) return secretCache[name]
  const { data, error } = await supabase.rpc('get_secret', { secret_name: name })
  if (error) { console.error(`get_secret(${name}):`, error.message); return null }
  if (data) secretCache[name] = data as string
  return (data as string) || null
}

function json(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}
